basePath: /v2
definitions:
  model.Article:
    properties:
      content:
        type: string
      desc:
        type: string
      title:
        type: string
    type: object
  model.Error:
    properties:
      message:
        type: string
    type: object
  model.Hello:
    properties:
      message:
        type: string
    type: object
host: github.com/ajit-go/swaggerexample
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a example of swagger with mux.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Home page
      parameters:
      - description: name search by q
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/model.Hello'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.Error'
      summary: Home page
  /articles:
    get:
      consumes:
      - application/json
      description: get Articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: list Articles
swagger: "2.0"
